repos:
- hooks:
  - id: fix-encoding-pragma
  - id: check-added-large-files
  - id: check-ast
  - id: check-case-conflict
  - id: check-docstring-first
  - id: check-json
  - id: pretty-format-json
  - id: check-merge-conflict
  - id: check-xml
  - id: check-yaml
  - id: debug-statements
  - id: detect-private-key
  - id: end-of-file-fixer
  - id: requirements-txt-fixer
  - id: trailing-whitespace
  repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.4.0
- hooks:
  - additional_dependencies:
    - flake8-typing-imports==1.10.0
    id: flake8
    args:
      - --max-line-length=120
  repo: https://gitlab.com/pycqa/flake8
  rev: 3.8.4
- hooks:
  - id: autopep8
  repo: https://github.com/pre-commit/mirrors-autopep8
  rev: v1.5.4
- hooks:
  - id: commitizen
    stages:
    - commit-msg
  repo: https://github.com/commitizen-tools/commitizen
  rev: v2.13.0
